name: Release Version

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Version to release"
        required: true

jobs:
  release_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write
    env:
      RELEASE_TAG: ${{ github.event.inputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        #TODO: Add a tag validation step to check that the tag is the next comparing with the previous

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Publish client
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ./gradlew :client:publish \
            --console=plain \
            -Pversion=$RELEASE_TAG

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u zumaxim --password-stdin

      - name: Build, tag, and push image to DockerHub
        run: |
          ./gradlew :server:jib \
            --console=plain \
            -Djib.to.tags=$RELEASE_TAG

      - name: "Create release"
        uses: "actions/github-script@v6"
        with:
          github-token: "${{ github.token }}"
          script: |
            const RELEASE_TAG = process.env.RELEASE_TAG
            try {
              await github.rest.repos.createRelease({
                name: `${RELEASE_TAG}`,
                body: `Server component is available on [DockerHub](https://hub.docker.com/repository/docker/zumaxim/xres/general): \`docker pull zumaxim/xres:${RELEASE_TAG}\``,
                draft: false,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: RELEASE_TAG,
              });
            } catch (error) {
              core.setFailed(error.message);
            }