name: Release Server Tag

on:
  workflow_dispatch:

jobs:
  release_job:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.inputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u zumaxim --password-stdin

      - name: Build, tag, and push image to DockerHub
        run: |
          ./gradlew :server:jib \
            --console=plain \
            -Dcontainer.tags=${{ steps.previous_tag.outputs.tag }}

      - name: "Create release"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ github.token }}"
          env:
            RELEASE_TAGE: ${{ steps.previous_tag.outputs.tag }}
          script: |
            try {
              await github.rest.repos.createRelease({
                name: "Server version ${{ process.env.RELEASE_TAG }}",
                body: "`docker pull zumaxim/xres:${{ process.env.RELEASE_TAG }}`",
                draft: false,
                generate_release_notes: true,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
              });
            } catch (error) {
              core.setFailed(error.message);
            }
